### ISSUE TITLE
Don't understand how to set up teamTokens

### ISSUE THREAD

**Issue by Alonski** [sozercan/vscode-slack#5]
Where exactly do I get the Team Token?

**Comment by sozercan** [comment]
Hi Alonski,

Go to preferences > user settings > and then add or append to right hand side

{
    "slack.teamToken": "YOUR-TOKEN-HERE"
}

looks like this:
![screen shot 2017-01-12 at 12 14 19](https://cloud.githubusercontent.com/assets/852750/21906603/c9e91074-d8c0-11e6-9cff-5db2b26dfca5.png)

**Comment by sozercan** [comment]
Looks like Slack changed their docs, you can get it here: https://api.slack.com/docs/oauth-test-tokens
