### ISSUE TITLE
Version 0.0.12 doesn't send Slack messages

### ISSUE THREAD

**Issue by KimeT** [sozercan/vscode-slack#8]
Hi,

After updating Slack extension to version 0.0.12 sending messages to Slack does not work anymore. It used to work before, but I'm not sure on which version.

Error messages:
- Slack: Send Message --> **ERROR** command 'slack.slackSendMsg' not found
- Slack: Send Selection --> **WARN** command 'slack.slackSendSelection' not found
- Slack: Upload Current File --> **WARN** command 'slack.slackUploadFileCurrent' not found

Some broken references etc.?

My VS Code version: ![image](https://cloud.githubusercontent.com/assets/3339395/22883168/820f7dba-f1f7-11e6-8f96-7ed7ef3f019a.png)

\- KimeT

**Comment by sozercan** [comment]
Sorry about that, should be fixed in 0.0.13 that is in the marketplace now.

Thanks for reporting!
